version: "3"
services:
  app:
    build: ./app
    image: ascendant-app:latest
    ports:
      - "5000:5000"
    networks:
      - ascendant
    volumes:
      - ./data/replays:/app/replays

  db: 
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ascendant
    networks:
      - ascendant
    volumes:
      - ./data/db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro

  parser:
    build: ./parser
    image: ascendant-parser:latest
    networks:
      - ascendant

  redis:
    image: redis:5-alpine
    networks:
      - ascendant

  celery-worker:
    build: ./celery-worker
    image: ascendant-worker:latest
    networks:
      - ascendant

networks:
  ascendant: